--- #YAML:1.0
name:                Liberty-Parser
version:             0.04
abstract:            Parser for Synopsys Liberty(.lib).
license:             ~
author:              
    - yorkwu <yorkwuo@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
