#! /bin/bash
BOOST="/home/ssingh/PhD/Boost/boost_1_33_0"
TCL="/usr/include"
LIBTCL="/usr/lib/libtcl8.5.so"
PARTITION_SOURCES="Partitioner/partition.cpp"
DISTRIBUTOR_SOURCES="Distributor/distributor.cpp"
KERNEL_SOURCES="Kernel/kernel.cpp"
TCL_SOURCES="TCL_Shell/cpptcl.cc TCL_Shell/diGAnaTCL.cpp"

SOURCES="$PARTITION_SOURCES $DISTRIBUTOR_SOURCES $KERNEL_SOURCES $TCL_SOURCES"

rm -rf mymodule.so
#echo "g++ -I $BOOST -I $TCL -I Partitioner -I Distributor -I Kernel -I TCL_Shell -L $LIBTCL -Wall $SOURCES -o mymodule.so"
g++ $PARTITION_SOURCES -c -fPIC -I $BOOST -I $TCL -I Partitioner -I Distributor -I Kernel -I TCL_Shell -L $LIBTCL -Wall -o part.o
g++ $DISTRIBUTOR_SOURCES -c -fPIC -I $BOOST -I $TCL -I Partitioner -I Distributor -I Kernel -I TCL_Shell -L $LIBTCL -Wall -o distro.o
g++ $KERNEL_SOURCES -c -fPIC -I $BOOST -I $TCL -I Partitioner -I Distributor -I Kernel -I TCL_Shell -L $LIBTCL -Wall -o kernel.o
g++ $TCL_SOURCES part.o distro.o kernel.o -fPIC -I $BOOST -I $TCL -I Partitioner -I Distributor -I Kernel -I TCL_Shell -L $LIBTCL -Wall -shared -o mymodule.so
#echo "g++ $SOURCES -shared -o mymodule.so -I $BOOST -I $TCL -I Partitioner -I Distributor -I Kernel -I TCL_Shell -L $LIBTCL" 
#g++ $SOURCES -shared -o mymodule.so -I $BOOST -I $TCL -I Partitioner -I Distributor -I Kernel -I TCL_Shell -L $LIBTCL 
