/* Generated by Yosys 0.5+292 (git sha1 6f9a6fd, gcc 4.6.3-1ubuntu5 -fPIC -Os) */

`include <master.v>

module top(in , clk, out);
input  in, clk;
output out;

BUF_X1 dbuf1 (.A(in), .Z(w1));
DFFRS_X1 dff (.D(w1), .CK(wclk), .Q(w2));
BUF_X1 dbuf2 (.A(w2), .Z(out));

BUF_X1 dbuf3 (.A(clk), .Z(wclk));

endmodule
