# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package timer_read_verilog;
use base qw(Exporter);
use base qw(DynaLoader);
package timer_read_verilogc;
bootstrap timer_read_verilog;
package timer_read_verilog;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package timer_read_verilog;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package timer_read_verilog;

*create_node = *timer_read_verilogc::create_node;
*create_edge = *timer_read_verilogc::create_edge;

# ------- VARIABLE STUBS --------

package timer_read_verilog;

1;
