# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package timerDesignInfo;
use base qw(Exporter);
use base qw(DynaLoader);
package timerDesignInfoc;
bootstrap timerDesignInfo;
package timerDesignInfo;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package timerDesignInfo;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package timerDesignInfo;

*create_node = *timerDesignInfoc::create_node;
*add_or_get_library = *timerDesignInfoc::add_or_get_library;
*add_or_get_cell = *timerDesignInfoc::add_or_get_cell;
*add_or_get_pin = *timerDesignInfoc::add_or_get_pin;
*add_pin = *timerDesignInfoc::add_pin;
*mark_clock = *timerDesignInfoc::mark_clock;
*add_pin_cap = *timerDesignInfoc::add_pin_cap;
*add_pin_relPin = *timerDesignInfoc::add_pin_relPin;
*getLibName = *timerDesignInfoc::getLibName;
*add_timing_sense = *timerDesignInfoc::add_timing_sense;
*add_timing_arc = *timerDesignInfoc::add_timing_arc;
*add_timing_type = *timerDesignInfoc::add_timing_type;
*create_circuit = *timerDesignInfoc::create_circuit;
*get_circuit = *timerDesignInfoc::get_circuit;
*add_pin_direction_io = *timerDesignInfoc::add_pin_direction_io;
*add_pin_direction = *timerDesignInfoc::add_pin_direction;
*perform_timing_analysis = *timerDesignInfoc::perform_timing_analysis;
*get_timing_arc = *timerDesignInfoc::get_timing_arc;
*get_pin_type = *timerDesignInfoc::get_pin_type;
*add_clock = *timerDesignInfoc::add_clock;
*add_IO_delay = *timerDesignInfoc::add_IO_delay;
*addReportObject = *timerDesignInfoc::addReportObject;

# ------- VARIABLE STUBS --------

package timerDesignInfo;

1;
