/* Generated by Yosys 0.5+292 (git sha1 6f9a6fd, gcc 4.6.3-1ubuntu5 -fPIC -Os) */

`include <master.v>

module top(in , clk, out);
input  [0:1] in; 
input  clk;
output out;
  BUF_X1 b1 (.A(in[0]), .Z(w1));
  BUF_X1 b2 (.A(in[1]), .Z(w2));
  AND2_X1 and1 (.A1(w1), .A2(w2a), .ZN(w3o));
  BUF_X1 b3 (.A(w3), .Z(wd4));
  DFFRS_X1 dff1 (.D(wd4), .CK(wc2), .Q(wo));
  BUF_X1 b4 (.A(w3), .Z(w4));
  BUF_X1 b5 (.A(w4), .Z(w5));
  AND2_X1 and2 (.A1(w5), .A2(w2), .ZN(w2a));
  BUF_X1 b6 (.A(wo), .Z(out));
  BUF_X1 b7 (.A(w3o), .Z(w3));
  BUF_X1 b8 (.A(w3o), .Z(w3a));
  DFFRS_X1 dff2 (.D(w3a), .CK(wc2), .Q());


  //Clock Path
  BUF_X1 c1 (.A(clk), .Z(wc1));
  BUF_X1 c2 (.A(wc1), .Z(wc2));
endmodule
