/* Generated by Yosys 0.5+292 (git sha1 6f9a6fd, gcc 4.6.3-1ubuntu5 -fPIC -Os) */

module top(in , clk, out);
input  in, clk;
output out;

BUF_X1 dbuf1_in (.A(in), .Z(w1));
DFFRS_X1 dff1 (.D(w1), .CK(wclk2), .Q(w2));
BUF_X1 dbuf2_in (.A(w2), .Z(w3));

BUF_X1 dbuf1_out (.A(w3), .Z(w4));
DFFRS_X1 dff2 (.D(w4), .CK(wclk1), .Q(w5));
BUF_X1 dbuf2_out (.A(w5), .Z(w6));

DFFRS_X1 dff3 (.D(w6), .CK(wclk2), .Q(w7));
BUF_X1 dbuf3_out (.A(w7), .Z(out));

BUF_X1 cbuf1 (.A(clk), .Z(wclk1));
BUF_X1 cbuf2 (.A(clk), .Z(wclk2));



endmodule
