/* Generated by Yosys 0.5+292 (git sha1 6f9a6fd, gcc 4.6.3-1ubuntu5 -fPIC -Os) */

`include <master.v>

module top(in , clk, out);
input  [0:1] in; 
input  clk;
output [0:1] out;
  BUF_X1 b1 (.A(in[0]), .Z(w1));
  BUF_X1 b2 (.A(w1), .Z(w2));
  BUF_X1 b3 (.A(w1), .Z(w3));
  BUF_X1 b4 (.A(w1), .Z(w4));
  BUF_X1 b5 (.A(w2), .Z(w6));
  BUF_X1 b6 (.A(w7), .Z(w8));
  BUF_X1 b7 (.A(w9), .Z(out[0]));
  BUF_X1 b8 (.A(w10), .Z(w11));
  BUF_X1 b9 (.A(w12), .Z(w13));
  BUF_X1 b10 (.A(in[1]), .Z(w14));
  BUF_X1 b11 (.A(w14), .Z(w15));
  BUF_X1 b12 (.A(w4), .Z(w5));

  AND2_X1 and1 (.A1(w6), .A2(w8), .ZN(w9));
  AND2_X1 and2 (.A1(w5), .A2(w15), .ZN(w16));
  AND2_X1 and3 (.A1(w11), .A2(w13), .ZN(out[1]));

  DFFRS_X1 dff1 (.D(w3), .CK(wc2), .Q(w7));
  DFFRS_X1 dff2 (.D(w9), .CK(wc4), .Q(w10));
  DFFRS_X1 dff3 (.D(w16), .CK(wc5), .Q(w12));

  //Clock Path
  BUF_X1 c1 (.A(clk), .Z(wc1));
  BUF_X1 c2 (.A(wc1), .Z(wc2));
  BUF_X1 c3 (.A(clk), .Z(wc3));
  BUF_X1 c4 (.A(wc3), .Z(wc4));
  BUF_X1 c5 (.A(clk), .Z(wc5));
endmodule
